package com.hafizdwp.explore_tokocrypto_coins_log

import com.hafizdwp.explore_tokocrypto_coins_log.data.local.table.Symbol

/**
 * @author hafizdwp
 * 21/05/2021
 **/

val listSymbol: List<String> = arrayListOf(
        Symbol("tokocrypto"),
        Symbol("vechain"),
        Symbol("ethereum"),
        Symbol("binancecoin"),
        Symbol("tron"),
        Symbol("cartesi"),
        Symbol("theta-fuel"),
        Symbol("zilliqa"),
        Symbol("ankr"),
        Symbol("cardano"),
        Symbol("dogecoin"),
        Symbol("safepal"),
        Symbol("wazirx"),
        Symbol("ripple"),
        Symbol("nano"),
        Symbol("trust-wallet-token"),
        Symbol("bittorrent-2"),
        Symbol("reef-finance"),

        Symbol("litecoin"),
        Symbol("1inch"),
        Symbol("algorand"),
        Symbol("my-neighbor-alice"),
        Symbol("alpha-finance"),
        Symbol("cosmos"),
        Symbol("auto"),
        Symbol("avalanche-2"),
        Symbol("bakerytoken"),
        Symbol("band-protocol"),

        Symbol("basic-attention-token"),
        Symbol("bitcoin-cash"),
        Symbol("bitcoin-cash-abc-2"),
        Symbol("bitcoin"),
        Symbol("burger-swap"),
        Symbol("pancakeswap-token"),
        Symbol("compound-coin"),
        Symbol("cream-2"),
        Symbol("certik"),
        Symbol("dash"),
        Symbol("dego-finance"),
        Symbol("polkadot"),

        Symbol("elrond-erd-2"),
        Symbol("enjincoin"),
        Symbol("filecoin"),
        Symbol("force-protocol"),
        Symbol("fantom"),
        Symbol("the-graph"),
        Symbol("hedera-hashgraph"),
        Symbol("rupiah-token"),
        Symbol("injective-protokol"),
        Symbol("just"),
        Symbol("kava"),
        Symbol("kyber-network-crystal"),
        Symbol("kusama"),
        Symbol("ethlend"),

        Symbol("lina"),
        Symbol("chainlink"),
        Symbol("loopring"),
        Symbol("terra-luna"),
        Symbol("decentraland"),
        Symbol("matic-network"),
        Symbol("moviebloc"),
        Symbol("origin-protocol"),
        Symbol("prometeus"),
        Symbol("qtum"),
        Symbol("thorchain"),
        Symbol("the-sandbox"),
        Symbol("shiba-inu"),
        Symbol("smooth-love-potion"),
        Symbol("havven"),
        Symbol("solana"),
        Symbol("serum"),
        Symbol("sun"),
        Symbol("sushi"),
        Symbol("swipe"),
        Symbol("theta-token"),
        Symbol("unifi-protocol-dao"),
        Symbol("uniswap"),
        Symbol("waves"),
        Symbol("wink"),
        Symbol("stellar"),
        Symbol("tezos"),
        Symbol("venus"),
        Symbol("yearn-finance"),
        Symbol("yfii-finance"),
        Symbol("0x"),
).map { it.id }
